---
- hosts: localhost
  become: true
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Check if Bazzite
      ansible.builtin.fail:
        msg: You might want to try https://bazzite.gg/...
      # while clearer i perfer the ansible_distribution variable...
      when: ansible_facts["distribution"] != "Bazzite"

    - name: Check for amd-smi
      ansible.builtin.shell: which amd-smi
      register: amd_smi_check

    - name: Fail if no AMD card detected
      ansible.builtin.fail:
        msg: checking...
      when:
        - amd_smi_check is none
        - amd_smi_check.stdout_lines != "/usr/sbin/amd-smi"

    - name: read the group file and make variable groups_user
      ansible.builtin.shell: cat /usr/lib/group
      register: groups_user

      # I probably should spin this out into two commands
    - name: Add required Groups for containers to render on GPU
      ansible.builtin.shell: usermod -aG video,render {{ ansible_env.SUDO_USER }}
      when:
        - groups_user.stdout_lines is not contains("render")
        - groups_user.stdout_lines is not contains("video")

    - name: check for container_use_devices boolean
      ansible.builtin.shell: getsebool container_use_devices
      register: container_gpu_bool

    # #Left the debug lines commented out in for easier troubleshooting later on.
    # - debug:
    #     msg: "{{ ansible_facts['env''SUDO_USER'] }} test"

    - name: Allow containers to use /dev/dri ( your AMD Gpu )
      ansible.builtin.shell: setsebool -P container_use_devices 1
      when:
        - container_gpu_bool.stdout is none
        - container_gpu_bool.stdout == "container_use_devices --> off"
